version: "3"

services:
  my-postgres-db:
    build: 
      context: services/database/.
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    #expose:
    #  - 5432
  app:
    build: 
      context: services/app
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000"
    expose:
     - 5000
    depends_on:
      - my-postgres-db
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - app
